# .github/workflows/release.yml
name: whisper2srt

on:
  pull_request:
  push:
    tags:
      - "v*"
    branches:
      - main
      - master
      - dev
      - qa
  # 手动触发
  workflow_dispatch:


permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  dockerbuilder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install
        run: |
          sudo apt install -y python3 python3-pip ffmpeg
          pip install openai-whisper
      - name: generate
        run: |
          whisper 712.opus --model large-v3 --model_dir ./ --output_format srt --prepend_punctuations ,.? --language Japanese --output_dir ./ --verbose True
      - name: saveSpace
        run: rm -rf /opt/hostedtoolcache
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: upload
          path: ${{ github.workspace }}/712.srt
          compression-level: 9 # max compression
      - name: release
        run: |
          time_var=$(date +"%Y%m%d-%H%M%S")
          gh release create $time_var --generate-notes
          gh release upload $time_var ${{ github.workspace }}/712.srt
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash